<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><!-- Core -->
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%><!--From-->

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" isELIgnored="false"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Online -->
<link rel="icon" href="./resources/images/favicon-04.png"
	type="image/x-icon">
<!-- bootstrap.min.js & jquery.min.js  -->
<link href=<c:url value="/resources/bootstrap/css/bootstrap.min.css"/>
	rel="stylesheet" type="text/css" />

<!-- Font Awesome -->
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- END  -->
<!-- AdminLTE -->

<link href=<c:url value="/resources/css/AdminLTE.min.css"/>
	rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link href=<c:url value="/resources/css/skins/_all-skins.min.css" />
	rel="stylesheet" type="text/css" />

<style type="text/css">
.myfa
{
	font-size: 30px;
}
@media (max-width:700px){
.myfa
{
	font-size: 20px;
}
}
@media (max-width:400px){
.myfa
{
	font-size: 10px;
}

}


input.gsc-input, .gsc-input-box, .gsc-input-box-hover,
	.gsc-input-box-focus, .gsc-search-button {
	box-sizing: content-box;
	line-height: normal;
}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Terms Of Use | Fundhouse</title>
<link rel="icon" href="./resources/images/favicon-04.png" type="image/x-icon">
</head>
<body class="hold-transition skin-blue layout-top-nav">
	<div class="wrapper">
	
	<jsp:include page="../mainHeader.jsp" flush="true"></jsp:include>
		<section class="section">
			<div class="container">
			
			<h2 class="text-center">TERMS OF USE</h2>
			<h3>13th December 2016</h3>
				<p>
					Welcome to www.fundhouse.co.in  These are the terms and conditions governing your use of the Site (herein after referred to as the &quot;Terms of Use&quot;). For the purpose of these Terms of Use, wherever the context so requires &quot;You&quot; or &quot;User&quot; shall mean any natural or legal person who has agreed to transact through the Site by providing the required registration data while registering on the Site as a 'Registered User' using the computer systems and/or any other electronic systems. The term &quot;We&quot;, &quot;Us&quot;, &quot;Our&quot; shall mean the Company (defined herein below).
				</p>
				<p>
					By accessing the Site through any of the electronic devices You acknowledge, accept and agree to the following terms of the Terms of Use, which are designed to make sure that this Site works for everyone. These Terms of Use is effective from the time You log in to the Site. By accepting these Terms of Use, You are also accepting and agreeing to be bound by the Privacy Policy which is available at <a href="http://www.fundhouse.co.in/privacyPolicy" target="_blank">www.fundhouse.co.in/privacypolicy</a> amended from time to time.
				</p>
				<p>
					By using the website, you agree to the terms and conditions of this privacy policy. If you do not agree with the terms and conditions of this privacy policy, please do not proceed further to use this website.
				</p>
				<h4><strong>BACKGROUND</strong></h4>
				<p>
					These Terms of Use is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
				</p>
				<p>
					This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Site. 
				</p>
				<h4><strong>OWNERSHIP</strong></h4>
				<p>	
					The Site is owned by Truealliance Consultancy Management India  Limited, a company incorporated under the Companies Act, 1956 with its registered office at New Delhi INDIA (hereinafter referred to as the &quot;Company&quot;).
				</p>
				<p>
					When You use the Services (defined herein below) provided by Us through the Site, You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such Services, and they shall be deemed to be incorporated into these Terms of Use and shall be considered as part and parcel of these Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior notice to You, whether written or otherwise. It is Your responsibility to keep yourself updated with the latest Terms of Use. Your continued use of the Site following the posting of changes will mean that You accept and agree to all the revisions made to the Terms of Use. As long as You comply with these Terms of Use, You are granted a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.
				</p>
				<p>
					We reserve all rights under intellectual property law in the Site and in any content that is on the Site or in the Services. Except as We may expressly state in writing, You shall not reproduce, reprint, publish, or otherwise exploit content or technology from the Site without our prior express consent.
				</p>
				<h4><strong>SCOPE AND INTENT OF THE TERMS OF USE</strong></h4>
				<p>
					You agree and understand that the Site is an internet enabled electronic platform that facilitates communication for multiple purposes such as identifying money changers to buy and sell foreign currency, identify financial institutions or individuals for a secured or unsecured loan, identify companies which offer insurance and; services which would be added by Us on a time to time basis (collectively known as &quot;Services&quot;). You further agree and understand that we do not endorse, market or promote any of the listings, postings or information, nor do we at any point in time come into possession of or directly engage in the currency exchange activities including buying, selling, exchanging or depositing currencies of any country and/or origin. Nor do we directly disburse loans, or issue an insurance. Fundhouse is merely a facilitator for bringing together borrowers, institutional lenders, individual lenders and insurers. Fundhouse is neither a money changer, insurer nor a financial institution. . While interacting with other users and/or service providers through our Site, with respect to any listing, posting or information we strongly encourage You to exercise reasonable diligence as You would normally apply in traditional off line channels and further practice judgment and common sense before committing to or completing any intended sale, purchase or exchange of currency or exchange, acceptance of a loan, lending a loan or subscribing to an insurance.
				</p>
				<h4><strong>REPRESENTATION AND WARRANTY</strong></h4>
				<p>
					You agree that You are the lawful owner having all rights, title and interest in Your information, and further agree that You are solely responsible and accountable for the information which You provide through this Site to any other user and/or service provider and that we act as a mere platform for your online distribution and publication of such information. 
					You agree that Your listing, posting, information and/or service offered through this Site shall:
				</p>
					<ol type="I" class="text-justify">
						<li>not be fraudulent, misrepresent, mislead pertaining to buying, selling, exchange etc of any illegal, counterfeit, stolen currency, securing a loan from a financial or individual investor or to claim insurance and/or services;</li>
						<li>shall not pertain to any currency or services of which You do not have the legal authority to possess, trade, exchange or market or lending of funds which are not legally recognized or accounted for under tax laws;</li>
						<li>shall not infringe any intellectual property, trade secret, or other proprietary right or rights of publicity or privacy of any third party;</li>
						<li>shall not consist of material that is an expression of bigotry, racism or hatred based on age, gender, race, religion, caste, class, lifestyle preference, and nationality and / or is in the nature of being derogatory, slanderous to any third party;</li>
						<li>shall not distribute viruses or any other technologies that may harm the Site or the interests or property of other users or impose an unreasonable load on the infrastructure or interfere with the proper working of the Site;</li>
						<li>shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade, exchange or attempt to exchange, buy or attempt to buy, sell or attempt to sell any services, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.</li>
					</ol>
				<h4><strong>COVENANTS</strong></h4>
				<p>
					It is agreed by You that if You use the Site by registering on the Site, You are responsible for maintaining the confidentiality of Your User ID, password, email address and for restricting access to Your computer, computer system, computer network and Your Site account, and You are responsible for all activities that occur under Your User ID and password. If You access the Site using any electronic device other than by registration on the Site, the Terms of Use remains applicable to You in the same manner as if You are a registered user on the Site.
				</p>
				<h4><strong>RIGHT TO USE INFORMATION</strong></h4>
				<p>
					By providing Us any information and/or documents through this Site You hereby grant Us the right to use such information for the purpose of providing the Service and copy, archive, distribute, abridge, transmit, display, translate or to pass such information to any other user holding an account on the Site or any of service providers registered on the Site. We shall reserve the right to incorporate such information as a collective work, database or archive.
				</p>
				<p>
					You will be required to enter a valid phone number while transacting through the site. By registering your phone number with us, you consent to be contacted by us and by the service provider or financial partner via phone calls (including ivrs calls) and/or sms notifications to provide you related updates pertaining to the transaction intended through the site. This consent will override any &quot;do not disturb&quot; (dnd) preferences set at your end with your telecom service provider. We will not use your personal information to initiate any promotional phone calls or sms. You agree that we may also provide you with notices and other information related to the services through electronic means including but not limited to sms, emails, mobile notifications etc as and when required.
				</p>
				<h4><strong>ROLES &amp; RESPONSIBILITIES</strong></h4>
				<p>
					We as a Company take all reasonable measures to investigate the background of the Service Providers registered with Us to ensure their authority to enter into the transactions contemplated herein through our Sit. However, You still agree and acknowledge that:
				</p>
				<ol type="I" class="text-justify">
					<li>
						All commercial/contractual terms are offered by and agreed to between any of the buyers/borrowers and sellers/financial institutions/individual lenders through our Site are not within the purview of the Company and the Company shall not be a party to such agreement whether directly or indirectly even if the Company has knowledge of such agreement. The Company does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the buyers/borrowers and sellers/financial institutions/individual lenders/insurance companies. Thus, the Company shall not be responsible for any non-performance or breach of any contract entered into between buyers/borrowers and sellers/financial institutions/individual lenders/insurance companies.	
					</li>
					<li>
						The Company does not make any representation or warranty as to specifics (such as legality, value, exchangeability, salability, RoI, premium etc) of the currencies or loan and insurance services proposed to be sold or offered to be sold or purchased or offered to be purchased or loan transactions agreed upon or offered to be agreed upon through the Site. The Company does not implicitly or explicitly support or endorse the sale or purchase or exchange of any currency or loan and insurance services on the Site, thus the Company accepts no liability for any errors or omissions, whether on behalf of itself or any third parties including the service providers registered with the Site.
					</li>
					<li>
						The Company cannot and does not guarantee that the concerned buyers, sellers, borrowers and/or lenders will perform any transaction concluded through the Site and the Company is not required to mediate or resolve any dispute or disagreement between such parties using the Site.
					</li>
					<li>
						You are advised to independently verify the bona fides of any particular user and/or service provider registered with the Site that You choose to deal with through the Site and use Your best judgment in that behalf.
					</li>
					<li>
						The Company does not at any point of time during any transaction between any intended buyers, sellers, borrowers, financial institutions, individual lenders and/or insurance companies through the Site come into or take possession of any of the currencies, loan amounts, insurance premiumsor other services offered by the seller/financial institutions/individual lenders/insurance companies nor does it at any point gain title to or have any rights or claims over the currencies, loans or other services offered by the seller/loan provider to the buyer/borrower. The Company is not responsible for any unsatisfactory or delayed performance of any services offered by the service providers/ financial institutions/individual lenders/insurance companies nor shall the Company be liable for any loss, damages, cost etc suffered by the User pertaining to or arising out of such services offered by the service providers/ financial institutions/individual lenders/insurance companies.
					</li>
					<li>
						Based on a verbal approval from the borrower, a credit check would be done with some of the banks/NBFCs such as ICICI Bank, Tata Capital, RBL Bank, Capital First, etc but not limited to the same. The credit check can also be undertaken by Fundhouse on behalf of the individual lenders.
					</li>
					<li>
						The Site is only a platform that can be utilized by users to reach a larger base of service providers registered on the Site to buy, sell and exchange currencies of different countries and related services, avail loans or any insurance policy.
					</li>
					<li>
						You release and indemnify the Company and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Site and specifically waive any claims that You may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, the Company cannot take responsibility or control the information provided by other users/service providers/borrowers/financial institutions/individual lenders/insurance companies which is made available on the Site. You may find other users/service providers/borrowers/financial institutions/individual lenders/insurance companies information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Site. Please note that there could be risks in dealing with underage persons or people acting under false pretense.
					</li>
					<li>
						When you receive and accept an offer from a bank, NBFC or individual lenders (or any entity) through Fundhouse, you should confirm interest rate, processing fees, tenure and other details with the relevant entity before finalizing the loan. You also confirm to check or have checked the loan deed/agreement for the above details before signing it. You may not hold Fundhouse responsible or accountable for any changes or errors in these details due your own failure to confirm said details during the finalization of loan offer verbally or on legal paper.
					</li>
					<li>
						You need to be sure when lending that the money advanced at your discretion. The company assumes that you have gone through the profile and are fully aware of all borrower details before advancing the loan.
					</li>
					<li>
						The company does not attest to or vouch for the complete authenticity of profile details, reasons for loan, references or any other information provided by the borrower with reference to the loan and as such will not be liable for any delays or defaults. You are advancing the loan at your sole risk and Fundhouse is not obligated to indemnify you against any losses due to defaults.
					</li>
					<li>
						The company relies on third party vendors to credit checks, bank statement analysis, social profile analysis, verification, eKYC and all related services not limited to these. The company interprets the reports on face value and is not liable for discrepancies arising from a fault in the processes of these third party vendors. You agree to not hold the company, its officers, directors and employees liable for any damage or loss arising out of any faulty/incorrect/incomplete information supplied by them.
					</li>
					<li>
						You agree to take all necessary precautions to ensure your financials are in good order before advancing a loan to ensure there is no claims mid-term for return of the principal amount. The company or the borrower will not be liable to honour any requests for return of principal amount before the end of the agreed tenure.
					</li>
				</ol>
				<h4><strong>RESTRICTIONS ON USE OF SITE</strong></h4>
				<p>
					Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are &quot;incompetent to contract&quot; within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Site. If You are a minor i.e. under the age of 21 years, You shall not register as a User of the Site and shall not transact through the Site. As a minor if You wish to use or transact through our Site, such use or transaction may be made by Your legal guardian or parents on the Site. If You access the Site either by registration on the Site or by any other means, not as an individual but on behalf of a legal entity, you represent that You are fully authorized to do so and the listing, posting or information placed on the site on behalf of the legal entity is Your responsibility and You agree to be accountable for the same to other users of the Site.
				</p>
				<h4><strong>LIMITATIONS OF LIABILITY</strong></h4>
				<p>
					This Site, all the materials and Services, included on or otherwise made available to You through this Site are provided on &quot;as is&quot; and &quot;as available&quot; basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, the Company does not warrant that:
				</p>
				<ul class="text-justify">
					<li>
						This Site will be constantly available, or available at all; or
					</li>
					<li>
						The information on this Site is complete, true, accurate or non-misleading
					</li>
					<li>
						The rate of interest for the loan offers is constant and will not change at the time of actual transaction between the borrower and the financial institution/individual lender
					</li>
					<li>
						The Services listed will be made available and will not change without notice to You.
					</li>
					<li>
						Electronic communication sent from Us are free of viruses or other harmful components.
					</li>
				</ul>
				<p>
					If you are dissatisfied with any of the services or with any of the terms of these Terms of Use, Your sole and exclusive remedy is to discontinue accessing the Site and using Services provided through the Site.
				</p>
				<p>
					Nothing on this Website constitutes, or is meant to constitute, advice of any kind. All the currencies sold, purchased and/or exchanged through the Site are governed by different state laws and are in principle subject to the Foreign Exchange Management Act, 1999 (including regulations applicable from time to time) Indian Contract Act, 1872 and Reserve Bank of India regulations in this regard. The Reserve Bank of India regulations as well as the IRDA regulations will be adhered to by the service providers. If the service provider/seller/financial institution/individual lender/insurance companies is unable to meet its obligations under the terms of agreement between the parties due to implications of different state laws, the seller/service provider/financial institution/individual lender/insurance companies will return the amount (if any) received in advance by the seller/service provider/financial institution/individual lender/insurance companies to the buyer/borrower for the transaction contemplated under such agreement between the seller/service provider and the buyer.
				</p>
				
				<h4><strong>THIRD PARTY ADVERTISEMENT</strong></h4>
				<p>
					We may include in the Site a link to or advertisement of or data from third party web sites or services or products (&quot;THIRD PARTY ADVERTISER&quot;). You agree that we are not responsible or liable for any content or other material on third party sites or services or products displayed through our Site. You also agree that we are not responsible for content or claims supplied by our third party advertiser. We are not responsible for any transactions or dealings between You and any third party advertiser. You agree that We are not responsible for any claim or loss occurred and attributable to third party advertiser.
				</p>
				
				<h4><strong>INDEMNITY</strong></h4>
				<p>
					You agree to defend, indemnify, and hold harmless us and our parent and other affiliated companies, and our respective employees, contractors, officers, directors, and agents from all liabilities, claims, and expenses, including attorney's fees, that arise from:
				</p>
				<ol type="I" class="text-justify">
					<li>Your use or misuse of this site;</li>
					<li>Your violation of any term of terms of use, including without limitation, your representation and/or warranty;</li>
					<li>Your violation of any third party right, including without limitation any copyright, trademark, trade secret or other property, or privacy right;</li>
					<li>Any claim that your content caused damage to a third party.</li>
				</ol>
				<p>
					We reserve the right, at our own expense, to assume the exclusive defence and control of any matter otherwise subject to indemnification by you, in which event you will co-operate with us in asserting any available defences.
				</p>
				
				<h4><strong>GOVERNING LAW &amp; JURISDICTION</strong></h4>
				<p>
					These Terms of Use shall be governed by the laws of Republic of India. You further agree that any disputes or claims that You may have against Us will be resolved by a court located in the city of Bangalore, state of Karnataka, India and You agree and submit to the exercise of personal jurisdiction of such courts for the purpose of litigating any such claim or action. By visiting the Site You agree to (i) waive all claims that you might otherwise have against us based on the laws of other jurisdictions, including Your own; (ii) irrevocably consenting to the exclusive jurisdiction of, and venue in, court of Bangalore in the state of Karnataka, India over any disputes or claims you have with us; and (iii) submitting yourself to the personal jurisdiction of such courts for the purpose of resolving any such disputes or claims.
				</p>
				
				<h4><strong>DISPUTE RESOLUTION</strong></h4>
				<p>
					Any dispute, differences or controversy of whatever nature and howsoever arising under or out of or in relation to these Terms of Use, or Privacy Policy and other notifications published on the Site (the 'Dispute') shall, in the first instance be attempted to be resolved amicably. Any Dispute which is not resolved amicably by conciliation within the period of 30 days shall be finally decided by arbitration in accordance with and subject to the provisions of the Arbitration and Conciliation Act, 1996. The Venue of such Arbitration shall be city of Bangalore, Karnataka, India and language of Arbitration shall be English. The award passed in such arbitration shall be final and binding upon the Parties to the dispute and You shall bear all costs and expenses (including attorney fee) related to such arbitration proceedings.
				</p>
				
				<h4><strong>SEVERABILITY &amp; ASSIGNMENT</strong></h4>
				<p>
					If any part of these Terms of Use or Privacy Policy is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of these Terms of Use and the remaining portions shall remain in full force and effect. You shall not assign any rights or obligations or liabilities created hereunder to any third party, however We reserve the right to assign any right or obligations or liabilities to any third party.
				</p>
				
				<h4><strong>RIGHT TO TERMINATE</strong></h4>
				<p>
					We may terminate Your access to the Site and its related Service, without cause or notice, which may result in the forfeiture and destruction of all information associated with Your account. If you wish to terminate Your account, You may do so by following the instructions on the Site. Any fees or charges for availing the Services paid to Us are non-refundable.
				</p>
				
				<h4><strong>CONTACT US</strong></h4>
				
				<p>
					For any query or assistance, feel free to contact us on the following address:
				</p>
				<p>Name of Person: Vikash Kumar Jain</p>
				<p>Designation: Director</p>
				<p>Email ID: <a href="mailto:director@fundhouse.co.in">director@fundhouse.co.in</a></p>
				
			</div>
		</section>
	<jsp:include page="../footer.jsp" flush="true"></jsp:include>
	</div>
</body>
</html>